name: Deploy (Vercel)

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Vercel Pull (pega envs)
        run: npx vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Vercel Build (produção)
        run: npx vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Vercel Deploy (produção)
        run: npx vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
